// Generated by CoffeeScript 1.9.3
(function() {
  var log, make_chart, test_function;

  log = console.log;

  test_function = function() {
    return log("Hello from chart-utils");
  };

  make_chart = function(ctx, label, unit, interval, n) {
    var i, j, labels, ref, stats;
    labels = new Array();
    for (i = j = 0, ref = n; 0 <= ref ? j <= ref : j >= ref; i = 0 <= ref ? ++j : --j) {
      labels.unshift((i * interval) + unit.toString());
    }
    stats = {
      type: 'line',
      data: {
        labels: labels,
        datasets: [
          {
            label: label,
            data: [0, 0, 0, 0, 0, 0],
            backgroundColor: "rgba(153,255,51,0.4)"
          }
        ]
      },
      options: {
        responsive: false
      }
    };
    chart = new Chart( ctx, stats );;
    return chart;
  };

}).call(this);
