// Generated by CoffeeScript 1.9.3
(function() {
  var $, Chart, Graph, bluebird, client, db, log, redis, trim_push;

  log = console.log;

  $ = require("jquery");

  redis = require('redis');

  client = redis.createClient(db = "0");

  bluebird = require('bluebird');

  Chart = require('chart.js');

  bluebird.promisifyAll(redis.RedisClient.prototype);

  bluebird.promisifyAll(redis.Multi.prototype);

  trim_push = function(array, value, size) {
    while (array.length >= size) {
      array.shift();
    }
    return array.push(value);
  };

  Graph = (function() {
    function Graph(id, key1, color) {
      var stats;
      this.id = id;
      this.key = key1;
      this.color = color;
      this.init_dom_element();
      stats = {
        type: 'line',
        data: {
          labels: ['3.5', '3.0', '2.5', '2.0', '1.5', '1.0', '0.5'],
          datasets: [
            {
              label: this.id,
              data: [0, 0, 0, 0, 0, 0, 0],
              backgroundColor: this.color
            }
          ]
        },
        options: {
          responsive: false
        }
      };
      this.chart = new Chart( this.ctx, stats );;
      this.chart_data = this.chart.data.datasets[0].data;
      this.init_update_iteration(500);
    }

    Graph.prototype.init_dom_element = function() {
      this.element = document.createElement('canvas');
      $(this.element).attr("id", this.id).attr("width", "500px").attr("height", "500px").appendTo('.graphs');
      return this.ctx = this.element.getContext('2d');
    };

    Graph.prototype.init_update_iteration = function(time) {
      var chart, key;
      chart = this.chart;
      key = this.key;
      return window.setInterval(function() {
        return client.getAsync(key).then(function(res) {
          trim_push(chart.data.datasets[0].data, res, 7);
          return chart.update();
        });
      }, time);
    };

    return Graph;

  })();

  exports.Graph = Graph;

}).call(this);
