// Generated by CoffeeScript 1.9.3
(function() {
  var $, Binary, Float, Graph, Range, bluebird, fs, init, log, redis, toml;

  $ = require("jquery");

  redis = require('redis');

  bluebird = require('bluebird');

  bluebird.promisifyAll(redis.RedisClient.prototype);

  bluebird.promisifyAll(redis.Multi.prototype);

  Graph = (require('./js/libs/graph.js')).Graph;

  Binary = (require('./js/libs/binary-indicator.js')).Binary;

  Float = (require('./js/libs/float-indicator.js')).Float;

  Range = (require('./js/libs/range.js')).Range;

  toml = require('toml');

  fs = require('fs');

  log = console.log;

  init = function(config) {
    var binaries, client, db, floats, graphs, ip, k, ref, ref1, ref2, test, v;
    client = redis.createClient(db = config.redis.db, ip = config.redis.ip);
    graphs = [];
    binaries = [];
    floats = [];
    log(config.graph);
    ref = config.graph;
    for (k in ref) {
      v = ref[k];
      graphs.push(new Graph(v[0], v[1], v[2], client));
    }
    ref1 = config.binary;
    for (k in ref1) {
      v = ref1[k];
      binaries.push(new Binary(v[0], v[1], client));
    }
    ref2 = config.float;
    for (k in ref2) {
      v = ref2[k];
      floats.push(new Float(v[0], v[1], client));
    }
    return test = new Range("Test", "redis-float-key", 0, 100, client);
  };

  fs.readFile('./traffic.toml', 'utf8', function(err, data) {
    if (err) {
      return console.log(err);
    }
    data = toml.parse(data);
    return init(data);
  });

}).call(this);
