// Generated by CoffeeScript 1.9.3
(function() {
  var $, Binary, Graph, bin_example, example, example2, log;

  $ = require("jquery");

  Graph = (require('./js/libs/graph.js')).Graph;

  Binary = (require('./js/libs/binary-indicator.js')).Binary;

  log = console.log;

  example = new Graph("testgraphid", "graph-test", "rgba(15, 86, 198, 0.4)");

  example2 = new Graph("Voltage", "voltage", "rgba(232, 42, 32, 0.6)");

  bin_example = new Binary("Ready_To_Shoot", "shoot");

}).call(this);
