// Generated by CoffeeScript 1.9.3
(function() {
  var $, Binary, Graph, bluebird, fs, init, log, redis, toml;

  $ = require("jquery");

  redis = require('redis');

  bluebird = require('bluebird');

  bluebird.promisifyAll(redis.RedisClient.prototype);

  bluebird.promisifyAll(redis.Multi.prototype);

  Graph = (require('./js/libs/graph.js')).Graph;

  Binary = (require('./js/libs/binary-indicator.js')).Binary;

  toml = require('toml');

  fs = require('fs');

  log = console.log;

  init = function(config) {
    var binaries, client, db, graphs, ip, k, ref, ref1, results, v;
    client = redis.createClient(db = config.redis.db, ip = config.redis.ip);
    graphs = [];
    binaries = [];
    log(config.graph);
    ref = config.graph;
    for (k in ref) {
      v = ref[k];
      graphs.push(new Graph(v[0], v[1], v[2], client));
    }
    ref1 = config.binary;
    results = [];
    for (k in ref1) {
      v = ref1[k];
      results.push(binaries.push(new Binary(v[0], v[1], client)));
    }
    return results;
  };

  fs.readFile('./traffic.toml', 'utf8', function(err, data) {
    if (err) {
      return console.log(err);
    }
    data = toml.parse(data);
    return init(data);
  });

}).call(this);
