// Generated by CoffeeScript 1.9.3
(function() {
  var $, Range, log;

  $ = require("jquery");

  log = console.log;

  Range = (function() {
    function Range(id, key1, lower, upper, client1) {
      this.id = id;
      this.key = key1;
      this.lower = lower;
      this.upper = upper;
      this.client = client1;
      this.init_dom_element();
      this.init_update_iteration(500);
    }

    Range.prototype.init_dom_element = function() {
      this.element = document.createElement('div');
      $(this.element).attr("id", this.id).appendTo('.range');
      return this.obj = radialIndicator('#' + this.id, {
        barColor: '#87CEEB',
        barWidth: 10,
        minValue: this.lower,
        maxValue: this.upper,
        initValue: this.lower,
        displayNumber: false
      });
    };

    Range.prototype.init_update_iteration = function(time) {
      var client, element, key, name, obj;
      element = $(this.indicator);
      key = this.key;
      client = this.client;
      name = this.id;
      element = $(this.element);
      obj = this.obj;
      return window.setInterval(function() {
        return client.getAsync(key).then(function(res) {
          return obj.animate(parseInt(res));
        });
      }, time);
    };

    return Range;

  })();

  exports.Range = Range;

}).call(this);
