// Generated by CoffeeScript 1.9.3
(function() {
  var $, ExampleElement, example, log;

  $ = require("jquery");

  log = console.log;

  ExampleElement = (function() {
    function ExampleElement(id, contents) {
      this.id = id;
      this.contents = contents;
      this.init_dom_element();
      this.init_update_iteration(500);
    }

    ExampleElement.prototype.init_dom_element = function() {
      this.element = $(".contents").append("div").attr("id", this.id);
      return this.element.text(this.contents);
    };

    ExampleElement.prototype.init_update_iteration = function(time) {
      return window.setInterval(function() {
        return log("test");
      }, time);
    };

    return ExampleElement;

  })();

  example = new ExampleElement("testid", "Test");

}).call(this);
